stages:
  - install
  - check
  - test-unit

default:
  interruptible: true

variables:
  NODE_VERSION: 22.14.0

.rule-mr: &rule-mr
  - if: &if-merge-request "$CI_MERGE_REQUEST_ID"
    when: on_success

.npm-cache: &npm-cache
  key:
    prefix: npm
    files:
      - package-lock.json
  paths:
    - node_modules/

.tests-node: &tests-node
  image: node:${NODE_VERSION}
  cache:
    <<: *npm-cache
    policy: pull

install:
  stage: install
  image: node:${NODE_VERSION}
  rules:
    - *rule-mr
    - when: never
  cache:
    <<: *npm-cache
    policy: pull-push
  script:
    - npm ci --ignore-scripts
    - node node_modules/@sentry/cli/scripts/install.js
    - npx patch-package
    - node scripts/generate-assets.js
    - node scripts/jitsi-ts-nocheck.js
  artifacts:
    expire_in: 12h
    paths:
      - dist/assets/

test:check:
  stage: check
  extends:
    - .tests-node
  rules:
    - *rule-mr
    - when: never
  script:
    - npm run check

test:i18n:
  stage: check
  extends:
    - .tests-node
  rules:
    - *rule-mr
    - when: never
  script:
    - ./scripts/precommit/i18n.sh

test:unit-tests:
  stage: test-unit
  extends: [.tests-node]
  rules:
    - *rule-mr
    - when: never
  script:
    - npm run test:ci
