name: prepare-ios-build
description: Action to prepare environment for ios build

runs:
  using: composite
  steps:
    - name: ci/setup-xcode
      uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: latest-stable

    - name: ci/prepare-mobile-build
      uses: ./.github/actions/prepare-mobile-build

    - name: ci/install-pods-dependencies
      shell: bash
      run: |
        echo "::group::install-pods-dependencies"
        npm run ios-gems
        echo "::endgroup::"
        
        echo "::group::debug-jitsi-pod-search"
        pod search JitsiMeetSDKLite --verbose
        echo "::endgroup::"
        
        echo "::group::pod-install"
        npm run pod-install
        echo "::endgroup::"

    - name: ci/checkout-private-repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: infomaniak/mobile-private
        token: ${{ env.MATTERMOST_BUILD_GH_TOKEN }}
        path: ${{ github.workspace }}/mobile-private

    - name: ci/append-fonts-to-build
      shell: bash
      run: |
        echo "::group::append-fonts-to-build"
        cp ${{ github.workspace }}/mobile-private/fonts/* assets/fonts/
        echo "::endgroup::"

    - name: Cache Pods
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
