def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']

  podfile_properties['ccacheEnabled'] == 'true'
end

ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_NEW_ARCH_ENABLED'] ||= '1'
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['buildReactNativeFromSource'] != 'true'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['buildReactNativeFromSource'] != 'true'
ENV['EXPO_USE_PRECOMPILED_MODULES'] ||= '1' if podfile_properties['buildExpoModulesFromSource'] != 'true'

platform :ios, podfile_properties['deploymentTarget'] || '16.6' #min_ios_version_supported
prepare_react_native_project!

Pod::UI.puts "Configuring Pod with statically linked Frameworks".green
use_frameworks! :linkage => :static

setup_permissions([
  "Camera",
  "Microphone",
  "Notifications",
  "PhotoLibrary"
])

if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
  config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
else
  config_command = [
    'node',
    '--no-warnings',
    '--eval',
    'require(\'expo/bin/autolinking\')',
    'expo-modules-autolinking',
    'react-native-config',
    '--json',
    '--platform',
    'ios'
  ]
end

config = use_native_modules!(config_command)

target 'kChat' do
  # Pods for Mattermost

  use_expo_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'simdjson', path: '../node_modules/@nozbe/simdjson', :modular_headers => true
  pod 'Gekidou', :path => './Gekidou'
  pod 'CocoaLumberjack', :modular_headers => true
  pod 'TurboLogIOSNative', :git => 'https://github.com/larkox/react-native-turbo-log-ios-native.git', :modular_headers => true
  # pod 'JitsiMeetSDKLite', :podspec => './JitsiMeetSDKLiteNoHermes.podspec'
  
end

target 'kChatNotificationService' do
  inherit! :search_paths
  pod 'TurboLogIOSNative', :git => 'https://github.com/larkox/react-native-turbo-log-ios-native.git', :modular_headers => true
  pod 'Sentry', '9.12.1'
  pod 'Gekidou', :path => './Gekidou'
end

target 'kChatShareExtension' do
  inherit! :search_paths
  pod 'Sentry', '9.12.1'
  pod 'Gekidou', :path => './Gekidou'
  pod 'OpenGraph', '1.4.1'
end

post_install do |installer|
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false,
    :ccache_enabled => ccache_enabled?(podfile_properties),
  )

  # Bitcode stripping for frameworks
  bitcode_strip_path = `xcrun --find bitcode_strip`.chop!

  def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    framework_path = File.join(Dir.pwd, framework_relative_path)
    if File.exist?(framework_path)
      command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
      puts "Stripping bitcode: #{command}"
      system(command)
    else
      puts "Framework not found, skipping: #{framework_path}"
    end
  end

  framework_paths = [
    "Pods/Giphy/GiphySDK/GiphyUISDK.xcframework/ios-arm64/GiphyUISDK.framework/GiphyUISDK",
  ]

  framework_paths.each do |framework_relative_path|
    strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
  end

  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |bc|
      bc.build_settings['SWIFT_VERSION']        = '5.9'
      bc.build_settings['OTHER_LDFLAGS']        = ['$(inherited)', '-ObjC']
      bc.build_settings['STRIP_SWIFT_SYMBOLS']  = 'NO'
      bc.build_settings['ENABLE_BITCODE']       = 'NO'
      # Force minimum deployment target for Xcode 26 compatibility
      if bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 16.0
        bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end

  end

  # ensure stdlib is embedded for Gekidou to work correctly in extensions
  %w[kChatNotificationService kChatShareExtension].each do |ext_name|
    target = installer.aggregate_targets.flat_map(&:user_project).flat_map(&:targets).find { |x| x.name == ext_name }
    next unless target
    target.build_configurations.each do |c|
      c.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
      c.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
    end
  end

  # Xcode 26: libc++ is no longer auto-linked for extension targets
  installer.aggregate_targets.each do |aggregate_target|
    if %w[Pods-kChatNotificationService Pods-kChatShareExtension].include?(aggregate_target.name)
      aggregate_target.xcconfigs.each do |config_name, config|
        config.other_linker_flags[:simple] |= ['-lc++']
        xcconfig_path = aggregate_target.xcconfig_path(config_name)
        config.save_as(xcconfig_path)
      end
    end
  end

  # make sure the main app is NOT extension-only
  app_target = installer.aggregate_targets.flat_map(&:user_project).flat_map(&:targets).find { |t| t.name == 'kChat' }
  if app_target
    app_target.build_configurations.each do |c|
      c.build_settings.delete('APPLICATION_EXTENSION_API_ONLY')
    end
  end

  # Xcode 26: fmt 11.0.2 consteval broken with Apple clang 21
  # https://github.com/fmtlib/fmt/issues/4740
  fmt_base = File.join(Dir.pwd, 'Pods', 'fmt', 'include', 'fmt', 'base.h')
  if File.exist?(fmt_base)
    FileUtils.chmod(0644, fmt_base)
    content = File.read(fmt_base)
    patched = content.gsub(
      /#elif defined\(__apple_build_version__\) && __apple_build_version__ < 14000029L/,
      '#elif defined(__apple_build_version__)'
    )
    if patched != content
      File.write(fmt_base, patched)
      Pod::UI.puts "Patched fmt/base.h for Xcode 26 compatibility".green
    end
  end
end
