// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import {type AppSchema, appSchema} from '@nozbe/watermelondb';

import {PlaybookRunSchema, PlaybookChecklistSchema, PlaybookChecklistItemSchema} from '@playbooks/database/schema';

import {
    CategorySchema,
    CategoryChannelSchema,
    ChannelInfoSchema,
    ChannelMembershipSchema,
    ChannelSchema,
    ConferenceSchema,
    ConferenceParticipantSchema,
    ConfigSchema,
    CustomEmojiSchema,
    DraftSchema,
    FileSchema,
    GroupSchema,
    GroupChannelSchema,
    GroupMembershipSchema,
    GroupTeamSchema,
    MyChannelSchema,
    MyChannelSettingsSchema,
    MyTeamSchema,
    PostInThreadSchema,
    PostSchema,
    PostsInChannelSchema,
    PreferenceSchema,
    ReactionSchema,
    RoleSchema,
    SystemSchema,
    TeamChannelHistorySchema,
    TeamMembershipSchema,
    TeamSchema,
    TeamSearchHistorySchema,
    ThreadSchema,
    ThreadInTeamSchema,
    ThreadParticipantSchema,
    TeamThreadsSyncSchema,
    UserSchema,
    ScheduledPostSchema,
    ChannelBookmarkSchema,
    CustomProfileAttributeSchema,
    CustomProfileFieldSchema,
} from './table_schemas';

export const serverSchema: AppSchema = appSchema({
    version: 7,
    tables: [
        PlaybookRunSchema,
        PlaybookChecklistSchema,
        PlaybookChecklistItemSchema,
        CustomProfileFieldSchema,
        CustomProfileAttributeSchema,
        ChannelBookmarkSchema,
        CategoryChannelSchema,
        CategorySchema,
        ChannelInfoSchema,
        ChannelMembershipSchema,
        ChannelSchema,
        ConferenceParticipantSchema,
        ConferenceSchema,
        ConfigSchema,
        CustomEmojiSchema,
        DraftSchema,
        FileSchema,
        GroupChannelSchema,
        GroupMembershipSchema,
        GroupSchema,
        GroupTeamSchema,
        MyChannelSchema,
        MyChannelSettingsSchema,
        MyTeamSchema,
        PostInThreadSchema,
        PostSchema,
        PostsInChannelSchema,
        PreferenceSchema,
        ReactionSchema,
        RoleSchema,
        ScheduledPostSchema,
        SystemSchema,
        TeamChannelHistorySchema,
        TeamMembershipSchema,
        TeamSchema,
        TeamSearchHistorySchema,
        TeamThreadsSyncSchema,
        ThreadInTeamSchema,
        ThreadParticipantSchema,
        ThreadSchema,
        UserSchema,
    ],
});
